# Generated by Django 5.1.2 on 2025-05-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='origin_city',
        ),
        migrations.AddField(
            model_name='city',
            name='origin_cities',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='flight_city.city'),
        ),
    ]
