# Generated by Django 5.1.2 on 2025-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EitaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('created_at', models.PositiveBigIntegerField(default=0)),
                ('last_login_at', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts_eita_user',
            },
        ),
    ]
