# Generated by Django 5.1.2 on 2025-11-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_eitauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='eitauser',
            name='eita_id',
            field=models.CharField(default='nothing', max_length=256, unique=True),
        ),
    ]
