# Generated by Django 5.1.2 on 2025-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_eitauser_eita_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eitauser',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
