# Generated by Django 5.1.2 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_eitauser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eitauser',
            name='initial_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]

