# Generated by Django 5.1.2 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_baleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('telegram_id', models.CharField(default='nothing', max_length=256, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.PositiveBigIntegerField(default=0)),
                ('last_login_at', models.PositiveBigIntegerField(default=0)),
                ('initial_message_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts_telegram_user',
            },
        ),
    ]

