# Generated by Django 5.1.2 on 2025-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('provider', models.CharField(max_length=256, unique=True)),
                ('redirect_number', models.IntegerField()),
            ],
        ),
    ]
