# Generated by Django 5.1.2 on 2025-04-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('emitter_uid', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=128)),
                ('payload_json', models.JSONField()),
                ('created_at', models.PositiveBigIntegerField()),
            ],
        ),
    ]
