# Generated by Django 5.1.2 on 2024-12-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMetadata',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('uploaded_at', models.PositiveBigIntegerField(null=True)),
                ('uploaded_by', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file_size_in_bytes', models.IntegerField()),
                ('upload_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_storage.uploadmetadata')),
            ],
        ),
    ]
