# Generated by Django 5.1.2 on 2025-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='file_link',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
