# Generated by Django 5.1.2 on 2025-04-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('airline', models.CharField(max_length=128)),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('departure_timestamp', models.BigIntegerField()),
                ('arrival_timestamp', models.BigIntegerField()),
                ('allowed_weight', models.IntegerField()),
                ('seat_class', models.CharField(choices=[('First Class', 'First Class'), ('Business Class', 'Business Class'), ('Premium Economy', 'Premium Economy'), ('Economy Class', 'Economy Class'), ('Basic Economy', 'Basic Economy')], default='Economy Class', max_length=20)),
                ('cheapest_price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('cheapest_redirect_url', models.CharField(blank=True, max_length=256, null=True)),
                ('cheapest_website_uid', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
                ('adult_price', models.FloatField()),
                ('child_price', models.FloatField()),
                ('infant_price', models.FloatField()),
                ('base_redirect_url', models.CharField(max_length=128)),
                ('one_adult_redirect_url', models.CharField(max_length=128)),
                ('two_adult_redirect_url', models.CharField(max_length=128)),
                ('remaining_seat', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('last_crawled_uid', models.CharField(max_length=128)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='flights.flight')),
            ],
        ),
    ]
