# Generated by Django 5.1.2 on 2025-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='seat_class',
            field=models.CharField(choices=[('First Class', 'First'), ('Business Class', 'Business'), ('Premium Economy', 'Premium Economy'), ('Economy Class', 'Economy'), ('Basic Economy', 'Basic Economy')], default='Economy Class', max_length=20),
        ),
        migrations.AlterField(
            model_name='website',
            name='adult_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='child_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='infant_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='one_adult_redirect_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='two_adult_redirect_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
