# Generated by Django 5.1.2 on 2025-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_seat_class_alter_website_adult_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='cheapest_redirect_url',
            new_name='cheapest_base_redirect_url',
        ),
        migrations.AddField(
            model_name='flight',
            name='cheapest_one_adult_redirect_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='cheapest_two_adult_redirect_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
