# Generated by Django 5.1.2 on 2025-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_website_base_redirect_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='base_redirect_url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='website',
            name='one_adult_redirect_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='two_adult_redirect_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
