# Generated by Django 5.1.2 on 2025-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_website_base_redirect_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cheapest_base_redirect_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cheapest_one_adult_redirect_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cheapest_two_adult_redirect_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
