# Generated by Django 5.1.2 on 2025-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_flight_cheapest_base_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
