# Generated by Django 5.1.2 on 2025-08-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
