# Generated by Django 5.1.2 on 2025-10-27 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks4', 'SOCKS4'), ('socks5', 'SOCKS5')], default='http', max_length=10)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=0.0)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('max_failures', models.IntegerField(default=5)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-success_rate', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rotation_strategy', models.CharField(choices=[('round_robin', 'Round Robin'), ('random', 'Random'), ('least_used', 'Least Used'), ('best_performance', 'Best Performance')], default='round_robin', max_length=20)),
                ('max_concurrent_requests', models.IntegerField(default=10)),
                ('health_check_interval', models.IntegerField(default=300)),
                ('failure_threshold', models.IntegerField(default=3)),
                ('cooldown_period', models.IntegerField(default=60)),
                ('health_check_url', models.CharField(default='https://httpbin.org/ip', max_length=500)),
                ('timeout', models.IntegerField(default=30)),
                ('retry_count', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='proxy_manager.proxy')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
