# Generated by Django 5.1.2 on 2025-04-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_fa', models.CharField(max_length=255, unique=True)),
                ('logo', models.CharField(max_length=255)),
                ('request_payload_structure', models.JSONField(blank=True, default=dict)),
                ('response_parsing_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('base_url', models.CharField(max_length=255)),
                ('redirect_url_template', models.CharField(max_length=255)),
                ('one_adult_url_template', models.CharField(blank=True, max_length=255, null=True)),
                ('two_adult_url_template', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=5)),
                ('is_supported', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='flight_crawler.website')),
            ],
            options={
                'unique_together': {('website', 'origin', 'destination')},
            },
        ),
    ]
