# Generated by Django 5.1.2 on 2025-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
