# Generated by Django 5.1.2 on 2025-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_crawler', '0002_alter_website_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='one_adult_url_template',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='redirect_url_template',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='website',
            name='two_adult_url_template',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
