# Generated by Django 5.1.2 on 2025-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_crawler', '0003_alter_website_one_adult_url_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
