# Generated by Django 5.1.2 on 2025-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
