# Generated by Django 5.1.2 on 2025-05-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
